### ISSUE TITLE
Adding user stories to README

### ISSUE THREAD

**Issue by kjetilk** [solid/user-stories#46]
Did we agree to add user stories to README? 

To me, that only seems to add overhead, as we need to maintain the README, and it then lacks classification mechanisms, i.e. we cannot add labels to them, we cannot assign them to people if we would chose that in the future, and also not assign to projects or milestones, if they are being worked on.

So, I don't see any advantages of that, only drawbacks.

**Comment by Mitzi-Laszlo** [comment]
What alternative are you proposing?

**Comment by kjetilk** [comment]
Actually, I would have kept it as it was, people submit their user stories as issues, and to see them, people use lists of issues.

**Comment by justinwb** [comment]
Most important is just that we can reference specific user stores by linking to them.

**Comment by kjetilk** [comment]
So, @Mitzi-Laszlo , we discussed in the data interop panel today, that we should construct use cases to motivate the projects, and the use cases could be constructed around user stories. For that, it is useful to link each user stories when writing use cases. As @justinwb said, the most important thing is to link them, but I think it would be helpful to re-open the issues, and then use the user story issues to link to. 

Lets have a conversation here what is the more convenient way to do it.

**Comment by megoth** [comment]
I want to bump this discussion, as I agree that we need to split up the user stories in the README into sensible chunks that can be managed and reviewed quicker. I propose readding the user stories as issues (I can do this if people agree that we should do it) and add labels to group them.

There are probably going to be many labels we can add to one issue, so we'll have to agree on what size and scope makes sense. To have something to being with I would suggest starting with "Authentication", "Authorization", "Auditing", "Data Control", "Accessibility", "Security", "Transparency", "Apps", "Pods", "IoT", "Guardian", and "Verifiability". On a personal note I would also like to add "Data Browser" as a label for issues we think are relevant to the Solid Data Browser.

This is never going to be a perfect system, but I think this way we would get more value from this repository.

**Comment by megoth** [comment]
I've talked with @Mitzi-Laszlo offline, and she's agreed that we'll have issues for each user story. After talking with @kjetilk offline as well, it should in many cases simply be about reopening closed issues, and create new ones for the extra user stories in README. I hope to have this done before the end of the week.

**Comment by megoth** [comment]
I've moved all user stories in README onto issues. Now closing this issue.
